### PR TITLE
Provide GitHub actions based build pipeline

### LINKED ISSUE #6: Create a Build Pipeline based on GitHub Actions
**Is your feature request related to a problem? Please describe.**
We need automated builds to verify Pull Requests and all kinds of commits more easily.

**Describe the solution you'd like**
As the project is hosted on GitHub, using GitHub Actions would provide the most transparency for contributors. A service hosted somewhere else could provide barriers.

### PR DESCRIPTION
**Pull request by kthoms**
This is an initial GitHub workflow that triggers the Maven build. The workflow was created with the GitHub workflow template for Maven and enhanced with inspirations from [JReleaser's build workflow](https://github.com/jreleaser/jreleaser/blob/main/.github/workflows/build.yml).

The build fails at this moment, but this is not fault to the pipeline, more to an instable state with failing tests.

Fixes #6, #24

### CODE REVIEW

**Comment by kthoms** [comment]
The build is not triggered here, but you can see it on my fork: [build log](https://github.com/kthoms/operaton/actions/runs/11451040253/job/31859605262?pr=1)

**Comment by javahippie** [comment]
Thanks for the contribution! I'm wondering about the flaky tests, never saw those issues locally. In the errors from your linked build logs it seems like the values have issues with timezone offsets 🤔

I approved the pipeline run for this MR and will check that output, too.

**Comment by kthoms** [comment]
Yes, the XML timezone offsets are an issue here. Should be a separate bug. After that the build should perform better.

**Comment by kthoms** [comment]
I have opened https://github.com/operaton/operaton/issues/24 to track the timezone issue

**Comment by javahippie** [comment]
The single remaining error could have happened due to my last merge (removing Telemetry, #1), I'm looking into that

**Comment by javahippie** [comment]
I have seen the current issue in the pipeline, when trying to build the project with `mvnd`. I think, this flag in the `maven.config` is the issue, as the project cannot be reliably built with a parallel execution: `--threads 2C`

**Comment by kthoms** [comment]
The build pipeline is now green. @javahippie Please check again.

**Comment by kthoms** [comment]
Added a build badge. Therefore I changed the workflow's name so that it reads "build" lower case, such as license.

Bildschirmfoto 2024-10-24 um 09 41 09

**Comment by javahippie** [comment]
Thank you very much for this contribution, this will make our builds much more stable and help other contributors :+1:

**Pull request merged**
