### PR TITLE
chore: Disabled Sonar analysis for PRs outside of operaton organisation [#80]

### PR DESCRIPTION
**Pull request by javahippie**

### CODE REVIEW

**Comment by kthoms** [comment]
We should consider to enable for PR builds later again, wenn we want to enforce the quality gate.
Please also consider my PR to just allow this step to fail. When Sonar is not able to be executed then this does not harm the build.

**Comment by javahippie** [comment]
I think we can add both for the moment, not failing the build seems reasonable to me

I don't see a way to re-enable the analysis for PR right now. The best we could do is having quality gates for the PRs from branches within the repo and not for external collaborators. To configure this we could check if "SONAR_TOKEN" is accessible in the workflow. If it is, then we run the analysis, if not we skip the whole step and save ~7 minutes of build time.

**Comment by javahippie** [comment]
Added a condition, checking if the workflow is running inside our org

**Comment by kthoms** [comment]
Rename PR title to "Disabled Sonar analysis for PRs outside of operaton organisation"?

**Pull request merged**
