### PR TITLE
[#67] Publish and archive surefire reports

### LINKED ISSUE #67: [build] Publish JUnit results in builds
**Is your feature request related to a problem? Please describe.**
When a PR causes test failures it is not on first sight which test is failing. You need to dig into the console output to look that up.
Further, it is not visible how many tests have been performed.

**Describe the solution you'd like**
Add a step to the build workflow that publishes the JUnit test results.

This is how it could look like in the action using the [junit-report-action](https://github.com/marketplace/actions/junit-report-action):

**Describe alternatives you've considered**
- Upload surefire reports as artifacts would create a zip and attach them to the build. We could consider this additionally.
- More GitHub actions exist that are doing similar things, e.g. [test-summary action](https://github.com/test-summary/action)

### PR DESCRIPTION
**Pull request by kthoms**
- use `junit-report-action` to publish test results and add a check to PR builds
- archive surefire reports

Fixes #67

### CODE REVIEW

**Comment by javahippie** [comment]
Nice, I thought about this during lunchtime, a nice coincidence :D

**Comment by kthoms** [comment]
There is a permission problem. I had this also in my test before, but then added permissions and it worked.
Bildschirmfoto 2024-10-28 um 14 45 09

Here the same branch is [built on my fork](https://github.com/kthoms/operaton/pull/5):
Bildschirmfoto 2024-10-28 um 14 46 35

**Comment by kthoms** [comment]
I'm not sure how to continue here. The error I'm seeing should not occur with the permissions set.

Here a [link to the appropriate hint](https://github.com/mikepenz/action-junit-report/issues/23#issuecomment-1412597753).

And on my fork this does not appear.

**Comment by kthoms** [comment]
We should see "2 successful checks" here.

**Comment by kthoms** [comment]
Let's try it. If this not working, we'll go the next step. Does not look as if it harms, the build was still green.

**Comment by javahippie** [comment]
I think it worked: https://github.com/operaton/operaton/actions/runs/11562223287

**Pull request merged**
