### PR TITLE
Fix instanceof check and cast with pattern matching in commons. (#85)

### PR DESCRIPTION
**Pull request by CBorowski-dev**

### CODE REVIEW

**Review by kthoms — CHANGES_REQUESTED** [review]
Could you try to avoid format changes? The javadocs should be untounched.

**Comment by CBorowski-dev** [comment]
Oh, I used a different IDE and didn't notice that "auto-format on save" or a similar feature was activated. Will undo the unwanted changes.

**Review by kthoms — APPROVED** [review]
Looks good now, thx.

**Review by javahippie — APPROVED** [review]
lgtm, too!

**Pull request merged**
