### PR TITLE
feat(build): Set up release workflow (#37)

### PR DESCRIPTION
**Pull request by kthoms**
Provide a `release` workflow and `jrelease.yaml` for automatic release builds.

relates to #37

### CODE REVIEW

**Comment by kthoms** [comment]
Currently work in progress, a copy from the recipe repo.

The current changelog, it will have to be tweaked with labelers, categories and rewriters:
[CHANGELOG.md](https://github.com/user-attachments/files/17910266/CHANGELOG.md)

**Comment by kthoms** [comment]
I would use this change as a starting point and would like to merge that. From then on, I could create a branch and operate on the branch to finalize the release workflow / configuration. In order to be able to do this, the workflow has once to be on master.

**Comment by hauptmedia** [comment]
Sure, we really need to get this working to push the beta-2 release out. It has so many changes and improvements compared to beta-1 that the release of beta-2 should be a priority.

**Comment by kthoms** [comment]
This should be a good starting point now.
@javahippie If you don't mind then I'll merge that.

**Comment by kthoms** [comment]
> ```
> platform:
>   replacements:
>     aarch_64: aarch64
> `` 
> ```

Copied this from JReleaser's configuration. Not sure when this will become relevant, likely when we start shipping executable distributions, e.g. Operaton as executable for Mac via homebrew.

Quite sure that we do not need this ATM.

**Comment by kthoms** [comment]
I'll work on the configuration anyway with the next steps. This is just the starting point.

**Pull request merged**
