### PR TITLE
Bump project version to 1.0.0-beta-2

### LINKED ISSUE #51: Increment project version to 1.0.0-beta-2
**Describe the bug**
The POMs still are using version `1.0.0-beta-1` although this version has already been deployed on Oct 16th.

**Expected behavior**
Version has been updated to `1.0.0-beta-2` in all POMs.

### PR DESCRIPTION
**Pull request by kthoms**
Fixes #51

### CODE REVIEW

**Comment by javahippie** [comment]
I think you ran into an issue with the multi module build: As long as the artifacts are not published, the resolution does not work well. Some of the artifacts use shading, and running `mvn test` does not reach the package phase for those modules, so they don't move the Classes to the new, shaded name. Unfortunately, they expose these shaded classes in their API, so the modules depending on them get a compile error. This could be fixed with replacing `mvn test` with `mvn package`, but it's a little bit dirty and violates the suggested maven lifecycles

**Comment by kthoms** [comment]
Right, this can be tricky. We will need to solve this chicken-egg-problem. I'll think about it.

**Comment by kthoms** [comment]
`qa-webapp-invoice-example:jar:1.0.0-beta-2` needs to be _installed_ to be resolvable. I would like to avoid using the install phase, but maybe we need a compromise. Let me check.

**Comment by kthoms** [comment]
The issue can be reproduced in a local build with `mvn package` after deleting Operaton artifacts from local Maven repo.

**Comment by kthoms** [comment]
The issue was introduced by #25 . We do not create empty Jars anymore.

The problem was that `WebappExampleApplication` from `starter-webapp` was located in `src/test/java`. Since there were no _main_ sources, the jar would be empty.

The jar is not produced, thus can't be resolved.

**Comment by kthoms** [comment]
Next issue:
```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.438 s <<< FAILURE! - in org.operaton.bpm.engine.rest.CustomJacksonDateFormatTest
Error:  org.operaton.bpm.engine.rest.CustomJacksonDateFormatTest  Time elapsed: 1.438 s  <<< ERROR!
org.jboss.shrinkwrap.resolver.api.InvalidConfigurationFileException: 
Found 12 problems while building POM model from /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: OR] Non-resolvable import POM: Failed to resolve POM for org.operaton.bpm:operaton-core-internal-dependencies:1.0.0-beta-2 due to Could not find artifact org.operaton.bpm:operaton-core-internal-dependencies:pom:1.0.0-beta-2 in JBoss public (https://repository.jboss.org/nexus/content/groups/public/) @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: OR] Non-resolvable import POM: Failed to resolve POM for org.operaton.bpm:operaton-bom:1.0.0-beta-2 due to Could not find artifact org.operaton.bpm:operaton-bom:pom:1.0.0-beta-2 in JBoss public (https://repository.jboss.org/nexus/content/groups/public/) @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: OR] 'dependencies.dependency.version' for commons-fileupload:commons-fileupload:jar is missing. @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: OR] 'dependencies.dependency.version' for commons-io:commons-io:jar is missing. @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: OR] 'dependencies.dependency.version' for org.jboss.spec.javax.servlet:jboss-servlet-api_3.0_spec:jar is missing. @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: OR] 'dependencies.dependency.version' for org.operaton.bpm:operaton-engine:jar is missing. @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: OR] 'dependencies.dependency.version' for junit:junit:jar is missing. @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: OR] 'dependencies.dependency.version' for org.mockito:mockito-core:jar is missing. @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: OR] 'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: ROR] 'dependencies.dependency.version' for org.slf4j:jcl-over-slf4j:jar is missing. @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: ROR] 'dependencies.dependency.version' for org.slf4j:jul-to-slf4j:jar is missing. @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
Error: ROR] 'dependencies.dependency.version' for org.assertj:assertj-core:jar is missing. @ org.operaton.bpm:operaton-engine-rest-core:1.0.0-beta-2, /home/runner/work/operaton/operaton/engine-rest/engine-rest/pom.xml
```

**Comment by kthoms** [comment]
I still don't get ATM why resolving the internal-dependencies BOM fails

**Comment by kthoms** [comment]
I had to disable `CustomJacksonDateFormatTest`. I don't see why this could cause the error resolving `operaton-core-internal-dependencies`.

**Pull request merged**
