### PR TITLE
[#78] Perform code coverage with JaCoCo on test execution 

### PR DESCRIPTION
**Pull request by kthoms**
Adds configuration of the jacoco-maven-plugin
- plugin version management in root pom.xml
- plugin configuration in parent pom.xml
Configure `argLine` properties of `maven-surefire-configurations` to prepend jacoco args

### CODE REVIEW

**Comment by javahippie** [comment]
Ha, you beat me to it, my local branch was only halfway there :D 

Thanks!

**Comment by javahippie** [comment]
This looks good, but I think Sonar wants one aggregate report for all the submodules which would be configured with the `report-aggregate` goal of the JaCoCo Maven plugin, tied to the verify phase:

https://community.sonarsource.com/t/coverage-test-data-importing-jacoco-coverage-report-in-xml-format/12151#multi-module-builds-3

**Comment by kthoms** [comment]
I have added the `report-aggregate` execution to the root POM. How do I see if it is working properly? The Sonar step is failing. Is there something missing?

**Comment by javahippie** [comment]
Hm, SonarQube should not be running at all for external contributors, as this PR cannot access our Secrets. I need to check my if-condition for that job again, it seems.

In your build logs I see Sonarqube logs claiming that it was not able to find any JaCoCo-XML files. The aggregate module is running multimple times (for every module?) but I don't see an aggregate file on the root-level target, when I run this build locally on my machine. 

This blog claims, that the aggregate only works in projects with direct dependencies to the other modules, which would be.. not ideal: https://blog.qaware.de/posts/sonarqube-and-jacoco/

**Comment by kthoms** [comment]
Thanks for the pointer. I'll fix that soon.

**Comment by kthoms** [comment]
Locally I'm getting now this output when executing the Sonar plugin at the end of the build:
```
[INFO] 10:55:48.455 SCM Publisher SCM provider for this project is: git
[INFO] 10:55:48.638 SCM Publisher 7909 source files to be analyzed
[INFO] 10:55:58.110 SCM Publisher 7908/7909 source files have been analyzed (done) | time=9472ms
[WARNING] 10:55:58.111 Missing blame information for the following files:
[WARNING] 10:55:58.375   * clients/java/client/pom.xml
[WARNING] 10:55:58.375 This may lead to missing/broken features in SonarCloud
[INFO] 10:55:58.562 CPD Executor 1737 files had no CPD blocks
[INFO] 10:55:58.562 CPD Executor Calculating CPD for 3010 files
[INFO] 10:55:58.995 CPD Executor CPD calculation finished (done) | time=433ms
[INFO] 10:56:02.345 Analysis report generated in 2419ms, dir size=84 MB
[INFO] 10:57:48.804 Analysis report compressed in 106459ms, zip size=29 MB
```

```
du -h -d 0 target/sonar
585M    target/sonar
```

The build pipeline now also is just executed when the `SONAR_TOKEN` is set. This prevents execution from other forks.

**Comment by javahippie** [comment]
Thanks, let's try it!

**Pull request merged**
