### PR TITLE
bugfix(webapp): Enable the bpmn.io badge in the bpmn-js and dmn-js re…

### LINKED ISSUE #338: BPMN.io watermark is not visible in Cockpit
From bpmn-js license:

>  The source code responsible for displaying the bpmn.io project watermark that
links back to https://bpmn.io as part of rendered diagrams MUST NOT be
removed or changed. When this software is being used in a website or application,
the watermark must stay fully visible and not visually overlapped by other elements.

Webapps should be fixed to show the watermark in bpmn-js and dmn-js.

### PR DESCRIPTION
**Pull request by javahippie**
…nderers

Fixes #338

### CODE REVIEW

**Comment by javahippie** [comment]
Before: 
grafik


After:
grafik

**Comment by datakurre** [comment]
You fixed it while I only managed to brew tea :tea:

**Comment by javahippie** [comment]
@datakurre Sorry, did not want to take this away from you, but while checking how hard it was to change this I already had 80% of the solution 😅

**Comment by javahippie** [comment]
Also: DMN

grafik

**Review by a-m-zill — APPROVED** [review]
LGTM 👍🏼  Thx @javahippie and @datakurre for the hint

**Pull request merged**
