### PR TITLE
[#49] Create CODE_OF_CONDUCT.md

### LINKED ISSUE #49: Add Code of conduct
**Is your feature request related to a problem? Please describe.**
The [project community standards insight](https://github.com/operaton/operaton/community) shows that the project is missing a Code of conduct. 

**Describe the solution you'd like**
Define a `CODE_OF_CONDUCT.md` . GitHub can propose one based on [Contributor Covenant](https://www.contributor-covenant.org/version/2/0/code_of_conduct/).

**Describe alternatives you've considered**
Write an own Code of conduct, maybe inspired by other major projects and using GPT.

### PR DESCRIPTION
**Pull request by kthoms**
The text is taken from [Contributor Covenant](https://www.contributor-covenant.org/version/2/0/code_of_conduct/).

Fixes #49

### CODE REVIEW

**Comment by javahippie** [comment]
Pinging @a-m-zill and @Kungi, too, because selection of a proper COC can have a lot of impact in the future.

**Comment by kthoms** [comment]
Yes, this is just a proposal yet. This should be carefully read and agreed.

**Review by a-m-zill — APPROVED** [review]
Thx @kthoms !!

**Comment by javahippie** [comment]
The COC text looks good to me, too

**Pull request merged**
