### PR TITLE
Fix instanceof check and cast with pattern matching in engine. (#85)

### PR DESCRIPTION
**Pull request by dirk-olmes**
related to #85

### CODE REVIEW

**Comment by javahippie** [comment]
Looks good to me, but unfortunately there are conflicts with the main branch

**Comment by dirk-olmes** [comment]
Err I merged the main branch before I started work early this morning.
In any case this is nothing worth fiddling with. Just discard the PR and I'll make another attempt later.

**Review by kthoms — APPROVED** [review]
Thank you

**Comment by kthoms** [comment]
@dirk-olmes I'm a bit confused about your last comment. Looks to me as this change is fine now. Any objections to merge it?

**Comment by javahippie** [comment]
I'm getting this:

grafik

**Comment by kthoms** [comment]
@javahippie I'm again confused. I see
Screenshot 319

Is anything missing? To me this looks fine. If you don't mind then I'll merge.

**Comment by javahippie** [comment]
Now we are confused together! If you can merge, go ahead! Seems to be a bug in GitHub

**Comment by javahippie** [comment]
To clarify, I was simply confused by GitHubs UX. My "Merge" button was set to "Rebase and Merge" by default. Rebasing the branch was not possible, but if I clicked on the "disabled" button, I was able to select "Squash and Merge", which was possible. Sorry for the confusion

**Pull request merged**
