### PR TITLE
Set up nightly build

### PR DESCRIPTION
**Pull request by kthoms**
- provide `nightly-build.yml`:
  - build with goals `clean install`
  - use local uncached repository
  - archive reports
  - archive distros
- Remove matrix build from main build pipeline
- Reports
  - dependency analysis
  - dependency updates
  - plugin updates
  - sloc

relates to https://github.com/operaton/operaton/issues/201

### CODE REVIEW

**Comment by kthoms** [comment]
@javahippie I'm not able to trigger the build for testing from the "Actions" page when selecting the nightly build workflow.
Am I missing some right?

There should by "Run workflow" button.

**Comment by javahippie** [comment]
> @javahippie I'm not able to trigger the build for testing from the "Actions" page when selecting the nightly build workflow. Am I missing some right?
> 
> There should by "Run workflow" button (see [docs](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow)).

Let me check the repository settings, I don't see it, either, might be a security / auth issue

**Comment by javahippie** [comment]
If I switch to the fitting branch and check the workflow, it complains that the workflow file is invalid:

```
Invalid workflow file: .github/workflows/nighly-build.yml#L20
You have an error in your yaml syntax on line 20
```

https://github.com/operaton/operaton/actions/runs/11928166253

I think this might be the root cause?

**Comment by hanshuebner** [comment]
The "Run Workflow" button for `workflow_dispatch` workflows will only appear after the workflow file has landed in the main branch.

**Comment by kthoms** [comment]
@javahippie I'll check the workflow again

@hanshuebner Thanks for the pointer. But how to test such workflow changes on branches? I would like to make sure that it does what it should before going to main.

**Comment by hanshuebner** [comment]
Am Mi., 20. Nov. 2024 um 23:48 Uhr schrieb Karsten Thoms <
***@***.***>:

> @hanshuebner <https://github.com/hanshuebner> Thanks for the pointer. But
> how to test such workflow changes on branches? I would like to make sure
> that it does what it should before going to main.
>
I think you need to push a dummy workflow with workflow_dispatch enabled to
main before you make changes to it on the branch, but I'm not sure.  I've
resorted to making workflow changes on the main branch mostly.

**Comment by kthoms** [comment]
I'll merge this now as a starting point. Potential fixes / enhancements will come soon.

**Pull request merged**
