### PR TITLE
openapi(tasks): include task state in response specification

### PR DESCRIPTION
**Pull request by hauptmedia**
Related to https://github.com/camunda/camunda-bpm-platform/issues/4683

Backported commit d27a7be1a70 from the camunda-bpm-platform repository.
Original author: Joaquín <joaquin.felici@camunda.com>

### CODE REVIEW

**Comment by hauptmedia** [comment]
Can someone with sufficients rights retrigger the workflow? The tests fail sporadically as described in #248

**Comment by a-m-zill** [comment]
@hauptmedia i have restarted the failed job and take a look on it now.

**Comment by hauptmedia** [comment]
@a-m-zill thanks you. Another thing i noticed yesterday: you used merge commits to merge a PR into the main branch. It would be really good if you could use rebase or squash (if it's multiple commits in one PR) for integrating the changes in main. This makes it a lot easier to follow changes in the main branch for everyone. Thanks!

**Comment by a-m-zill** [comment]
@javahippie has informed me about this also and he has changed the configuration of the repo, so we can only use squash now.

**Review by a-m-zill — APPROVED** [review]
👍🏼

**Pull request merged**
