### PR TITLE
skip maven install on windows machines

### PR DESCRIPTION
**Pull request by WoSchmo**
On my Windows machine I had problems with the install plugin in the changed project poms. This solves that.

### CODE REVIEW

**Comment by javahippie** [comment]
Hi @WoSchmo thanks for the report and PR! 

Could you elaborate which errors you saw on Windows? The install phase is pretty late in the Maven Lifecycle, so I wonder if `mvn verify` would be enough as a workaround, and we should instead try and make the install plugin work on Windows, so developers are able to install their dev version into the local repository?

**Comment by kthoms** [comment]
I think we should know about the root cause. Disabling install does not sound as a solution. We had cases where specific modules needed to be skipped, but this should be done now. Recently the "run" distro had been added which caused such a problem, but this got fixed with https://github.com/operaton/operaton/pull/343.

Please report a bug with the error that you are experiencing. And try on latest `main`, please.

**Comment by WoSchmo** [comment]
OK, I tried it again with the current main and it works. Thank you @kthoms for the update. I will close the MR! Sorry for the confusion!

**Comment by kthoms** [comment]
Good to hear that it is working!

**Pull request closed without merging**
